config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :companies do
    resources :employees, only: :index
  end

  resources :employees

  root to: 'companies#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# Application record for common model methods
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
# frozen_string_literal: true

# To store companies
class Company < ApplicationRecord
  scope :requirement_satisfied, -> { where(requirement_satisfied: true) }
  scope :requirement_unsatisfied, -> { where(requirement_satisfied: false) }

  has_many :employees,
           inverse_of: :company,
           dependent: :nullify

  acts_as_nested_set counter_cache: :sub_company_count

  def satisfies_requirement?
    total_employees_count >= required_employees_count
  end

  def update_validity
    self.requirement_satisfied = true if satisfies_requirement?
  end

  def update_validity!
    update_validity
    save!
  end

  def increment_total_emp_count
    self.total_employees_count += 1
  end

  def increment_total_emp_count!
    increment_total_emp_count
    save!
  end

  def decrement_total_emp_count
    self.total_employees_count -= 1
  end

  def decrement_total_emp_count!
    decrement_total_emp_count
    save!
  end

  def increment_ancestral_emp_count!
    ActiveRecord::Base.transaction do
      self_and_ancestors.each do |company|
        company.increment_total_emp_count!
        company.update_validity!
      end
    end
  end

  def decrement_ancestral_emp_count!
    ActiveRecord::Base.transaction do
      self_and_ancestors.each do |company|
        company.decrement_total_emp_count!
        company.update_validity!
      end
    end
  end
end

app/models/employee.rb
# frozen_string_literal: true

# To Store employees
class Employee < ApplicationRecord
  belongs_to :company, counter_cache: true

  after_create_commit :increment_company_emp_count
  after_destroy_commit :decrement_company_emp_count

  def increment_company_emp_count
    company.increment_ancestral_emp_count!
  end

  def decrement_company_emp_count
    company.decrement_ancestral_emp_count!
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

# controller to handle companies
class CompaniesController < ApplicationController
  def new
    @company = Company.new
    @all_companies = Company.all
  end

  def create
    @company = Company.new(company_params)

    respond_or_redirect(@company)
  end

  def index
    @companies = Company.requirement_satisfied if params[:valid].present?
    @companies = Company.requirement_unsatisfied if params[:invalid].present?

    @companies ||= Company.all.order(:lft)
    @companies_tree = build_hash_tree(@companies)
  end

  def show
    @company = Company.find params[:id]
    @company_tree = build_hash_tree(@company.self_and_descendants)
  end

  def destroy; end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :parent_id,
      :required_employees_count,
      :country
    )
  end

  def respond_or_redirect(company)
    respond_to do |format|
      if company.save
        format.html do
          redirect_to(company,
                      notice: 'Company was successfully created.')
        end
      else
        format.html { render action: 'new', notice: 'An error occurred' }
      end
    end
  end

  def build_hash_tree(tree_scope)
    tree = ActiveSupport::OrderedHash.new
    id_to_hash = {}

    tree_scope.each do |ea|
      h = id_to_hash[ea.id] = ActiveSupport::OrderedHash.new
      (id_to_hash[ea.parent_id] || tree)[ea] = h
    end
    tree
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

# Controller for handling employees
class EmployeesController < ApplicationController
  before_action :set_company

  def new
    @employee = Employee.new
  end

  def create
    employee = Employee.new(employee_params)

    respond_or_redirect(employee)
  end

  def show
    @employee = Employee.includes(:company).find params[:id]
  end

  def index
    @employees = if params[:company_id]
                   Employee.where(company_id: params[:company_id])
                 else
                   Employee.all
                 end
  end

  private

  def employee_params
    params.require(:employee).permit(:company_id)
  end

  def set_company
    return unless params[:company_id]

    @company = Company.find params[:company_id]
  end

  def respond_or_redirect(employee)
    respond_to do |format|
      if employee.save
        format.html do
          redirect_to(employee,
                      notice: 'Employee was successfully created.')
        end
      else
        format.html { render action: 'new', notice: 'An error occurred' }
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helper methods
module ApplicationHelper
  # rubocop:disable Rails/OutputSafety
  def render_hash_tree(tree)
    content_tag :ul do
      tree.each_pair do |node, children|
        name = node.name
        employee_count = "#{node.employees_count}/#{node.required_employees_count}"
        requirement_satisfied = node.requirement_satisfied
        content = [name, employee_count, requirement_satisfied].join(' ')
        content += render_hash_tree(children) if children.any?
        concat content_tag(:li, content.html_safe)
      end
    end
  end
  # rubocop:enable Rails/OutputSafety
end

app/views/companies/index.html.erb
<%= render_hash_tree(@companies_tree) %>
<%= link_to 'Add Company', new_company_path %>
<br>
<%= link_to 'Add Employee', new_employee_path %>
<br>
<%= link_to 'View valid companies', companies_path(valid: true) %>
<br>
<%= link_to 'View invalid companies', companies_path(invalid: true) %>
<br>
<%= link_to 'View all companies', companies_path %>

app/views/companies/new.html.erb
<%= simple_form_for @company do |f| %>
  <%= f.input :name %>
  <%= f.label 'Parent' %>
  <%= f.collection_select :parent_id, Company.order(:name),:id,:name, include_blank: true  %>
  <%= f.input :required_employees_count, default: 0 %>
  <%= f.input :country %>
  <%= f.button :submit %>
<% end %>

app/views/companies/show.html.erb
<ul>
  <li>Company name: <%= @company.name %></li>
  <li>Company country: <%= @company.country %></li>
  <li>Company Employee count: <%= @company.employees_count %></li>
</ul>
Company Hierarchy
<%= render_hash_tree(@company_tree) %>

<%= link_to 'Show companies employees', company_employees_path(@company) %>
<br>
<%= link_to 'See all companies', companies_path %>
<br>
<%= link_to 'Create another company', new_company_path %>

app/views/employees/index.html.erb
<ul>
  <% @employees.each do |employee| %>
    <li>Employee id: employee.id</li>
    <li>Employee company: employee.company.name</li>
  <% end %>
</ul>

app/views/employees/new.html.erb
<%= simple_form_for @employee do |f| %>
  <%= f.label 'Company' %>
  <%= f.collection_select :company_id, Company.order(:name), :id, :name, include_blank: true  %>
  <%= f.button :submit%>
<% end %>

app/views/employees/show.html.erb
<ul>
  <li>Employee id: <%= @employee.id %></li>
  <li>Company name: <%= @employee.company.name %></li>
  <li>Company country: <%= @employee.company.country %></li>
</ul>

<br>
<%= link_to 'Show Company', company_path(@employee.company) %>
<br>
<%= link_to 'Show all Companies', companies_path %>
<br>
<%= link_to 'Create another employee', new_employee_path %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>